### PR TITLE
find fqdn across platforms

### LINKED ISSUE #3044: Failing windows build of `PEcAn.ED2`: bug in `fqdn()`?
### Bug Description

The windows build of `PEcAn.ED2` on r-universe is [currently failing](https://github.com/r-universe/pecanproject/actions/runs/3094086051/jobs/5007429303) because of a failing test in test.met2model.R.  The only thing that makes sense to me that would cause this is if `fqdn()` returns NULL or a length 0 vector on Windows.  I don't have a Windows machine to do local testing on.  Tests for `fqdn()` would help debug this.

### PR DESCRIPTION
**Pull request by dlebauer**
## Description

Add `as.character(Sys.info()["nodename"])`  if no env variable FQDN and `hostname -f`  return empty strings.

## Motivation and Context

hostname doesn't work on Windows. Fixes #3044

**Perhaps a simpler option** 

replace function with `fqdn <- function() as.character(Sys.info()["nodename"])`

## Review Time Estimate

- [ ] Immediately
- [ ] Within one week
- [x] When possible

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue) 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [x] My name is in the list of CITATION.cff
- [x] I have updated the CHANGELOG.md.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: base/remote/R/fqdn.R [hunk 1]
```diff
@@ -19,9 +19,5 @@
 ##' @examples
 ##' fqdn()
 fqdn <- function() {
-  if (Sys.getenv("FQDN") != "") {
-    Sys.getenv("FQDN")
-  } else {
-    system2("hostname", "-f", stdout = TRUE)
-  }
+  as.character(Sys.info()["nodename"])
```
Comment (dlebauer) [inline base/remote/R/fqdn.R:22]: If there is a case when the environment variable FQDN should be checked first we could replace this with

```r
  fqdn <- Sys.getenv("FQDN")
  if (fqdn == "") {
    fqdn <- system2("hostname", "-f", stdout = TRUE)
  } 
  if (fqdn == "") {
    fqdn <- as.character(Sys.info()["nodename"])
  }
  return(fqdn)

Comment (robkooper) [reply base/remote/R/fqdn.R:22]: main reason for the FQDN is for an easy way to override the hostname, for example in the case of docker and kubernetes.

**Review by robkooper — CHANGES_REQUESTED** [review]

File: base/remote/R/fqdn.R (hunk 1 above)
Comment (dlebauer) [reply base/remote/R/fqdn.R]: OK now FQDN will override
