### PR TITLE
Fix API to correctly use x_var from request in plotResults

### LINKED ISSUE #3328: Can’t change x-axis on web interface plots
### Bug Description

Web interface graphs always have time on the x-axis - changing the X-axis variable seems to have no effect

### To Reproduce

1. Go to pecan web interface https://pecan-dev.ncsa.cloud/pecan/08-finished.php?workflowid=99000000001&hostname=docker&loglines=20
2. Conduct a run or go to an existing successful run from https://pecan-dev.ncsa.cloud/pecan/history.php
3. Click on graphs —> x-axis —> anything but ’time’
4. Click ‘plot’
5. Notice that x axis is always’time’

## Expected behavior

Changing variable on x axis should change plot 

## Screenshots

image

## Machine (please complete the following information):

 - Server pecan-dev.ncsa.cloud
 - OS: Linux
 - Version PEcAn v1.8.0

## Additional context

not sure if this is a necessary feature - usually we want ‘time’ on x axis, this is mostly for diagnostics, and data is available for download so that users can do custom analysis.

### PR DESCRIPTION
**Pull request by AritraDey-Dev**
## Description

The issue was that the API endpoint for plotting results always used `"time"` as the x-axis variable, regardless of what was passed from the web ui. This made the x-axis selection in the UI non-functional.

I fixed this by modifying the `plotResults` function to correctly extract and use the `xvar` parameter passed from the request object `(req$args$xvar)`. Previously, the value of x_var was being `hardcoded` or ignored, leading to time being used unconditionally.

Now, the function dynamically checks if xvar is provided in the request and uses that as the x_var in the plotting logic:
```
x_var <- ifelse(!is.null(req$args$xvar), req$args$xvar, "time")
```
This ensures that the front-end selection for the x-axis is respected in the plots generated by the API.

**screenshots**:
Screenshot from 2025-05-24 16-32-26
Screenshot from 2025-05-24 16-32-37

## Motivation and Context

fixes #3328 

## Review Time Estimate

- [ ] Immediately
- [ ] Within one week
- [ ] When possible

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue) 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] My name is in the list of CITATION.cff
- [x] I agree that PEcAn Project may distribute my contribution under any or all of
	- the same license as the existing code,
	- and/or the BSD 3-clause license.
- [ ] I have updated the CHANGELOG.md.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: apps/api/R/runs.R [hunk 1]
```diff
@@ -273,7 +274,7 @@ plotResults <- function(req, run_id, year, y_var, x_var="time", width=800, heigh
   
   # Plot & return
   filename <- paste0(Sys.getenv("DATA_DIR", "/data/"), "workflows/temp", stringi::stri_rand_strings(1, 10), ".png")
-  PEcAn.visualization::plot_netcdf(datafile, y_var, x_var, as.integer(width), as.integer(height), year=year, filename=filename)
```
Comment (robkooper) [inline apps/api/R/runs.R:276]: will merge, but there was no need to swap these parameters.

**Review by robkooper — APPROVED** [review]

File: apps/api/R/runs.R (hunk 1 above)
Comment (AritraDey-Dev) [reply apps/api/R/runs.R:276]: Yes, I changed the order just for consistency with the `PEcAn.visualization::plot_netcdf` inputs—though it is the same thing.
