### PR TITLE
fix qqline misuse in metric_lmDiag_plot

### LINKED ISSUE #3937: Fix logical operator, type check, and qqline misuse across db and benchmark modules
Hey, was going through some files and spotted a few bugs worth fixing.

1st one is in dbfile.move() around line 330 of base/db/R/dbfiles.R — the file type check uses | instead of &&, which makes the condition always TRUE. So both "clim" and "nc" immediately hit the error block, basically making the function unusable for its intended inputs.
r# current

> if (file.type != "clim" | file.type != "nc") {

2nd is in insert.format.vars() around line 40 of base/db/R/insert.format.vars.R — skip defaults to 0 (numeric) but the guard checks is.character(skip), so every default call logs an error. The check should be is.numeric instead.

> rif(!is.character(skip)){
  logger.error("Skip must be of type character")
}

3rd is in metric_lmDiag_plot() around line 30 of modules/benchmark/R/metric_lmDiag_plot.R — stats::qqline() is being passed inside aes() but it's a base R side-effect function that returns NULL, so the Q-Q line just never shows up silently. Fix would be to manually compute the slope and intercept from quantiles and pass them straight to geom_abline().

> rp2 <- p2 + ggplot2::geom_abline(ggplot2::aes(stats::qqline(.data$.stdresid)))
Happy to open a PR with all three fixes if that works!

Planning to open a PR tomorrow with fixes for all three, will reference this issue there.

### PR DESCRIPTION
**Pull request by omkarrr2533**
stats::qqline() is a base R side-effect function that returns NULL — wrapping it in aes() means the Q-Q line never shows up. Replaced with an explicit slope/intercept calculation passed directly to geom_abline().

Fix : #3937

### CODE REVIEW

File: modules/benchmark/R/metric_lmDiag_plot.R [hunk 1]
```diff
@@ -23,7 +23,12 @@ metric_lmDiag_plot <- function(metric_dat, var, filename = NA, draw.plot = FALSE
   
   p2 <- ggplot2::ggplot(fit, ggplot2::aes(stats::qqnorm(.data$.stdresid)[[1]], .data$.stdresid)) 
   p2 <- p2 + ggplot2::geom_point(na.rm = TRUE)
```
Comment (infotroph) [inline modules/benchmark/R/metric_lmDiag_plot.R]: Calculation from these lines is now discarded -- is that intentional?

Comment (omkarrr2533) [reply modules/benchmark/R/metric_lmDiag_plot.R]: No, that wasn't intentional those two lines are now dead code since p2 gets fully reassigned right after. Removed them in the latest push. Thanks for catching it! 👍

File: modules/benchmark/R/metric_lmDiag_plot.R [hunk 2]
```diff
@@ -21,10 +21,13 @@ metric_lmDiag_plot <- function(metric_dat, var, filename = NA, draw.plot = FALSE
   p1 <- p1 + ggplot2::ggtitle("Residual vs Fitted Plot") 
   p1 <- p1 + ggplot2::theme_bw()
   
-  p2 <- ggplot2::ggplot(fit, ggplot2::aes(stats::qqnorm(.data$.stdresid)[[1]], .data$.stdresid)) 
-  p2 <- p2 + ggplot2::geom_point(na.rm = TRUE)
-  p2 <- p2 + ggplot2::geom_abline(ggplot2::aes(stats::qqline(.data$.stdresid))) 
-  p2 <- p2 + ggplot2::xlab("Theoretical Quantiles") 
+  p2 <- ggplot2::ggplot(
+  data = data.frame(sample = stats::na.omit(ggplot2::fortify(fit)$.stdresid)),
+  ggplot2::aes(sample = sample)
```
Comment (infotroph) [inline modules/benchmark/R/metric_lmDiag_plot.R]:
```suggestion
    data = data.frame(sample = stats::na.omit(ggplot2::fortify(fit)$.stdresid)),
    ggplot2::aes(sample = sample)
```

**Review by infotroph — APPROVED** [review]
Thanks! This looks good

For the record when I test this locally with ggplot2 4.0.2 I get a deprecation warning from ggplot2::fortify, but I think that was present before this patch as well (because it called fortify on the qqnorm outputs under the hood). We can discuss a fix for that separately.
