### PR TITLE
Allow `ud_convert()` to work with class "difftime" (fix for #3012)

### LINKED ISSUE #3012: units::set_units cannot work with class "difftime"
### Bug Description
Recent `udunits2` to `units` change introduced a bug to one of our common met process pipeline. [This met2CF.csv line ](https://github.com/PecanProject/pecan/blob/develop/modules/data.atmosphere/R/met2CF.csv.R#L246)is now throwing an error:
```
Error in UseMethod("set_units") : 
  no applicable method for 'set_units' applied to an object of class "difftime"
```

### To Reproduce
Try the demo run or see:

```
days_since_1700 <- as.POSIXct(c("2003-01-01 00:00:00 UTC", "2003-01-01 00:30:00 UTC")) - lubridate::ymd_hm("1700-01-01 00:00")
as.numeric(mean(PEcAn.utils::ud_convert(diff(days_since_1700), "d", "s")))
```

### Proposed solution

We can change class from `difftime` to `numeric` before conversion:
```
mean(PEcAn.utils::ud_convert(as.numeric(diff(days_since_1700)), "d", "s"))
```
or any other solutions are welcome.

### PR DESCRIPTION
**Pull request by Aariq**
## Description

Fixes #3012 .  Checks if argument `x` is difftime, and if it is converts it to a `units` object with `as_units()`.  Units are inferred from the class, so argument `u1` isn't actually used in the conversion in this case.  UI is a little weird here, but seems like this is mostly an internal function so probably better than adding argument defaults and allowing `u1` to be `NULL` or something like that.

## Review Time Estimate

- [ ] Immediately
- [ ] Within one week
- [x] When possible

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue) 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My change requires a change to the documentation.
- [x] My name is in the list of CITATION.cff
- [x] I have updated the CHANGELOG.md.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by dlebauer — CHANGES_REQUESTED** [review]
Looks great- just make sure to update the change log!

File: base/utils/R/ud_convert.R [hunk 1]
```diff
@@ -3,15 +3,21 @@
...
+##'   to be supplied and needs to be convertible to `u2` for consistency.
 ##' @param u2 string parseable as the units to convert to
 ##' 
 ##' @return numeric vector with values converted to units in `u2`
 ##' @export
 ud_convert <- function(x, u1, u2) {
   stopifnot(units::ud_are_convertible(u1, u2))
-  x1 <- units::set_units(x, value = u1, mode = "standard")
+  if(inherits(x, "difftime")) {
+    x1 <- units::as_units(x)
```
Comment (infotroph) [inline base/utils/R/ud_convert.R:17]: I'm nervous about ignoring `u1` here -- I don't know how often units(x) and u1 will mismatch in practice, but when they do it means at a minimum that the user's expectations are wrong and the earlier we alert them the better.

Maybe something like...?
```suggestion
    stopifnot(units::as_units(units(x)) == units::as_units(u1))
    x1 <- units::as_units(x)
```

**Comment by Aariq** [comment]
> Looks great- just make sure to update the change log!

I can do this, but I'll just point out that the changelog already includes a bullet about this function being re-factored for this version.  This bug was an unforseen side-effect of that refactoring

**Review by infotroph — APPROVED** [review]

**Review by dlebauer — APPROVED** [review]
